module.exports = {
  env: {
    node: true
  },
  plugins: [
    "fp"
  ],
  rules: {
    'fp/no-arguments': 'warn',
    'fp/no-delete': 'warn',
    'fp/no-mutating-assign': 'warn',
    'fp/no-mutating-methods': 'warn',
    'no-var': 'error',

    'block-scoped-var': 'error',
    'block-scoped-var': 'error',
    'camelcase': 'error',
    'complexity': ['error', 9],
    'consistent-return': 'warn',
    'dot-location': ['error', 'property'],
    'eol-last': 'error',
    'eqeqeq': ['error', 'smart'],
    'indent': ['error', 2],
    'linebreak-style': ['error', 'unix'],
    'no-case-declarations': 'error',
    'no-cond-assign': 'error',
    'no-constant-condition': 'error',
    'no-debugger': 'error',
    'no-div-regex': 'error',
    'no-dupe-args': 'error',
    'no-dupe-keys': 'error',
    'no-else-return': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-invalid-this': 'error',
    'no-loop-func': 'error',
    'no-mixed-spaces-and-tabs': 'error',
    'no-multi-spaces': 'error',
    'no-nested-ternary': 'error',
    'no-new-func': 'error',
    'no-new-require': 'error',
    'no-new-wrappers': 'error',
    'no-proto': 'error',
    'no-redeclare': ['error', { builtinGlobals: true }],
    'no-self-compare': 'error',
    'no-trailing-spaces': 'error',
    'no-undef': 'error',
    'no-underscore-dangle': 'error',
    'no-unused-vars': 'error',
    'no-use-before-define': 'error',
    'no-void': 'error',
    'no-with': 'error',
    'object-curly-spacing': ['error', 'always'],
    'quotes': ['error', 'single', 'avoid-escape'],
    'radix': ['error', 'always'],
    'semi': ['error', 'always'],
    'space-in-parens': ['error', 'never'],
    'strict': ['error', 'global'],
    'vars-on-top': 'error'
  }
};
